apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-filestore-pvc
spec:
  storageClassName: ""  
  volumeName: odoo-filestore  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

